### ISSUE TITLE
Netlify won't build due to config error in _config.yml, causing all checks to fail.

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#30]
Commit f4100c7e73dc26eb6aa7623eea4df2db4dd5067d introduced changes to the _config.yml, causing `bundle exec jekyll build` to crash unexpectedly.

Here's the [log](https://app.netlify.com/sites/frosty-rosalind-8e3002/deploys/61df3031c8fb610008a4bdc6) from Netlify:

```
6:47:15 AM: $ bundle exec jekyll build
6:47:16 AM:                     ------------------------------------------------
6:47:16 AM:       Jekyll 4.1.1   Please append `--trace` to the `build` command 
6:47:16 AM:                      for any additional information or backtrace. 
6:47:16 AM:                     ------------------------------------------------
6:47:16 AM: /opt/build/cache/bundle/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': **(/opt/build/repo/_config.yml):** found character that cannot start any token while scanning for the next token at line 7 column 19 (Psych::SyntaxError)
	from /opt/build/cache/bundle/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:129:in `safe_load_file'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:167:in `read_config_file'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:198:in `block in read_config_files'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:195:in `each'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:195:in `read_config_files'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:118:in `configuration'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:44:in `configuration_from_options'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:29:in `process'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /opt/build/cache/bundle/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
	from /opt/build/cache/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'
	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
	from /opt/build/cache/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by yyjlincoln** [comment]
Fixed. I will close this issue shortly as it has been fixed.
